#! /bin/sh

### Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

### Monitors
bspc monitor -d I II III IV

### BSPWM Configuration

bspc config border_width            2
bspc config window_gap              8
# bspc config top_padding             0

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# Colors
bspc config focused_border_color    "#7AA2F7"
bspc config normal_border_color     "#A9B1D6"
# bspc config active_border_color     "#444b6a"

bspc config focus_follows_pointer   true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
