#! /bin/sh

### Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
# Toggle kb layouts
setxkbmap -option grp:alt_shift_toggle -layout us,latam &
# Launch polybar
$HOME/.config/polybar/launch.sh &
# Start notifications
dunst &
$HOME/.fehbg


### Monitors
bspc monitor -d I II

### BSPWM Configuration
bspc config border_width            2
bspc config window_gap              4
# bspc config top_padding             0

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# Colors
bspc config focused_border_color    "#7AA2F7"
bspc config normal_border_color     "#A9B1D6"

bspc config focus_follows_pointer   true

# Rules
bspc rule -a discord desktop='^2' follow=off focus=off
