# Documentation 
#  -> https://starship.rs/config/

format = """
[](#a3aed2)\
$username\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[ ](bg:#394260 fg:#769ff0)\
$git_branch\
[](fg:#394260 )

[󱞪 ](fg:#769ff0)\
"""


# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#090c0c bg:#a3aed2"
style_root = "bg:#AD8EE6"
format = '[ $user ]($style)'
disabled = false

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "  "
"Downloads" = "  "
"Music" = "  "
"Images" = "  "
"dev" = "  "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[$symbol $branch](fg:#769ff0 bg:#394260)]($style)'
